CREATE TABLE LOCATON (
    BID     VARCHAR(25),
    LOC    VARCHAR(50),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);

CREATE TABLE HOURS (
    BID            VARCHAR(25),
    OPENHRS        NUMBER,
    CLOSEHRS       NUMBER,
    WORKDAY        VARCHAR(10),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);