DROP TABLE LOCATON CASCADE CONSTRAINTS;
DROP TABLE HOURS CASCADE CONSTRAINTS;
DROP TABLE ATTRIB CASCADE CONSTRAINTS;
DROP TABLE REVIEWS CASCADE CONSTRAINTS;
DROP TABLE SUB_CATEGORIES  CASCADE CONSTRAINTS;
DROP TABLE MAIN_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE BUSINESS CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_MAIN_CATEGORIES CASCADE CONSTRAINTS;

